// checkpoint(JSON) -> weights.ts 변환 스크립트.
//
// 메인 트랙은 학습을 하지 않고 "변환만" 한다. (Python 불필요, Bun 으로 실행)
// 옵셔널 트랙 O3 가 만든 JSON checkpoint 를 읽어, 각 레슨이 import 할 TS 모듈로 내보낸다.
//   model/srcnn.checkpoint  -> lessons/18-srcnn-super-resolution/model/srcnn-weights.ts
//   model/fsrcnn.checkpoint -> lessons/19-fsrcnn-super-resolution/model/fsrcnn-weights.ts
//
// 레이아웃 계약은 model/architecture.md, 타입은 src/core/sr-model.ts 참고.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

interface Target {
  ckpt: string;
  out: string;
  varName: string;
}

const TARGETS: Target[] = [
  {
    ckpt: "model/srcnn.checkpoint",
    out: "lessons/18-srcnn-super-resolution/model/srcnn-weights.ts",
    varName: "srcnn",
  },
  {
    ckpt: "model/fsrcnn.checkpoint",
    out: "lessons/19-fsrcnn-super-resolution/model/fsrcnn-weights.ts",
    varName: "fsrcnn",
  },
];

function f32(arr: number[]): string {
  return `new Float32Array([${arr.join(",")}])`;
}

function emit(varName: string, data: any): string {
  const layers = data.layers
    .map(
      (l: any) =>
        `  { name: ${JSON.stringify(l.name)}, type: ${JSON.stringify(l.type)}, ` +
        `inC: ${l.inC}, outC: ${l.outC}, kh: ${l.kh}, kw: ${l.kw}, ` +
        `activation: ${JSON.stringify(l.activation)}, ` +
        `weight: ${f32(l.weight)}, bias: ${f32(l.bias)} }`,
    )
    .join(",\n");
  const deconv = data.deconv ? `\n  deconv: ${JSON.stringify(data.deconv)},` : "";
  return (
    `// AUTO-GENERATED by scripts/make-weights.ts — 직접 수정하지 마세요.\n` +
    `// 출처 checkpoint: 옵셔널 트랙 O3 의 PyTorch 학습 결과.\n` +
    `import type { SrModel } from "@core/sr-model.ts";\n\n` +
    `export const ${varName}: SrModel = {\n` +
    `  model: ${JSON.stringify(data.model)},\n` +
    `  scale: ${data.scale},\n` +
    `  preUpscale: ${JSON.stringify(data.preUpscale)},${deconv}\n` +
    `  layers: [\n${layers}\n  ],\n};\n`
  );
}

let done = 0;
for (const t of TARGETS) {
  if (!existsSync(t.ckpt)) {
    console.log(`건너뜀: ${t.ckpt} 없음 (옵셔널 트랙 O3 에서 학습 후 export)`);
    continue;
  }
  const data = JSON.parse(readFileSync(t.ckpt, "utf8"));
  mkdirSync(dirname(t.out), { recursive: true });
  writeFileSync(t.out, emit(t.varName, data));
  const params = data.layers.reduce(
    (s: number, l: any) => s + l.weight.length + l.bias.length,
    0,
  );
  console.log(`생성: ${t.out}  (layers=${data.layers.length}, params=${params})`);
  done++;
}
if (done === 0) {
  console.log("변환할 checkpoint 가 없습니다. 옵셔널 트랙 O3(SRCNN/FSRCNN 학습)을 참고하세요.");
}
